apiVersion: batch/v1
kind: Job
metadata:
  name: job-authorino-ssl-env
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: run
          image: {{ .Values.image }}
          command:
            - /bin/bash
            - /scripts/run.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: job-authorino-ssl-env
            defaultMode: 0555
