apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhoai-extras
rules:
  - apiGroups:
      - opendatahub.io
    resources:
      - dashboards
    verbs:
      - get
      - patch
  - apiGroups:
      - kuadrant.io
    resources:
      - kuadrants
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhoai-extras
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhoai-extras
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhoai-extras-kuadrant-pods
  namespace: {{ .Values.kuadrant.podNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhoai-extras-kuadrant-pods
  namespace: {{ .Values.kuadrant.podNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhoai-extras-kuadrant-pods
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhoai-extras-authorino-deployments
  namespace: {{ .Values.authorino.namespace }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhoai-extras-authorino-deployments
  namespace: {{ .Values.authorino.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhoai-extras-authorino-deployments
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
