subscriptions:
  code:
    models:
      nemotron-3-nano-30b-a3b:
        namespace: llm
        tokenRateLimits:
          - limit: 200000
            window: 1m
    groups:
      - name: system:authenticated:oauth
