install-rhoai:
  operators:
    rhods-operator:
      channel: stable-3.3

dataScienceCluster:
  version: v2
  components:
    aipipelines:
      managementState: Removed
    feastoperator:
      managementState: Removed
    kserve:
      modelsAsService:
        managementState: Managed
    ray:
      managementState: Removed
    trainer:
      managementState: Removed
    trainingoperator:
      managementState: Removed

dashboardConfig:
  disableKServeMetrics: false
  genAiStudio: true
  modelAsService: true

hardwareProfiles:
  l40s:
    node:
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: l40-gpu
          effect: NoSchedule
    displayName: NVIDIA L40s
    cpu:
      min: 1
      max: 6
      default: 2
    memory:
      min: 2Gi
      max: 48Gi
      default: 16Gi
    gpu:
      nvidia.com/gpu:
        max: 1
        displayName: NVIDIA L40s
