dataScienceCluster:
  version: v2
  components:
    kserve:
      managementState: Managed
      nim:
        managementState: Managed
      modelsAsService:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
    llamastackoperator:
      managementState: Managed
    trainingoperator:
      managementState: Removed

dataScienceClusterInitialization: null

dashboardConfig:
  disableModelRegistry: false
  disableModelCatalog: false
  disableKServeMetrics: false
  genAiStudio: true
  modelAsService: true
  disableLMEval: false

modelServerSizes: null

notebookSizes: null
