{{- range .Values.models }}
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{ .name }}-maas-auth
  labels:
    app.kubernetes.io/component: llminferenceservice-maas-auth
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: models-as-a-service
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ .name }}-kserve-route
  rules:
    authentication:
      maas-tokens:
        kubernetesTokenReview:
          audiences:
          - https://kubernetes.default.svc
          - maas-default-gateway-sa
    authorization:
      maas-access:
        kubernetesSubjectAccessReview:
          user:
            expression: auth.identity.user.username
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              value: llminferenceservices
            name:
              expression: request.path.split("/")[2]
            namespace:
              expression: request.path.split("/")[1]
            verb:
              value: post
{{- end }}
