{{- range .Values.models }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: {{ .name }}-view-role
rules:
- apiGroups:
  - serving.kserve.io
  resourceNames:
  - {{ .name }}
  resources:
  - llminferenceservices
  verbs:
  - get
{{- end }}
