---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tier-to-group-mapping
  namespace: redhat-ods-applications
data:
  tiers: |
    {
      "free": ["system:authenticated"],
      "premium": ["system:authenticated"],
      "enterprise": ["system:authenticated"]
    }
