---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tier-to-group-mapping
  namespace: redhat-ods-applications
data:
  tiers: |
    [
      {"name": "free", "allowedGroups": ["system:authenticated"]},
      {"name": "premium", "allowedGroups": ["system:authenticated"]},
      {"name": "enterprise", "allowedGroups": ["system:authenticated"]}
    ]
