apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-free-users
{{- if .Values.tiers.free.users }}
users:
  {{- toYaml .Values.tiers.free.users | nindent 2 }}
{{- else }}
users: []
{{- end }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-premium-users
{{- if .Values.tiers.premium.users }}
users:
  {{- toYaml .Values.tiers.premium.users | nindent 2 }}
{{- else }}
users: []
{{- end }}

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-enterprise-users
{{- if .Values.tiers.enterprise.users }}
users:
  {{- toYaml .Values.tiers.enterprise.users | nindent 2 }}
{{- else }}
users: []
{{- end }}

