{{- range $plan, $priority := dict "free" 10 "premium" 20 }}
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  name: maas-{{ $plan }}-subscription
  namespace: models-as-a-service
spec:
  owner:
    groups:
      {{- range (index $.Values.plans $plan).ownerGroups }}
      - name: {{ . }}
      {{- end }}
  modelRefs:
    - name: {{ $.Values.modelName | default "nemotron-3-nano-30b-a3b" }}
      namespace: llm
      tokenRateLimits:
        {{- toYaml (index $.Values.plans $plan).tokenRateLimits | nindent 8 }}
  priority: {{ $priority }}
{{- end }}
