apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-api-maas-namespace
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maas-api
subjects:
- kind: ServiceAccount
  name: maas-api
  namespace: maas-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-api-model-access
  labels:
    app.kubernetes.io/part-of: models-as-a-service
rules:
- apiGroups:
  - serving.kserve.io
  resources:
  - llminferenceservices
  - inferenceservices
  verbs:
  - post
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-api-model-access
  labels:
    app.kubernetes.io/part-of: models-as-a-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maas-api-model-access
subjects:
- kind: ServiceAccount
  name: maas-api
  namespace: redhat-ods-applications
- kind: ServiceAccount
  name: maas-api
  namespace: maas-api
