{{- if and .Values.rocketchat.enabled (not .Values.rocketchat.existingSecret) }}
---
# RocketChat credentials secret (created only if existingSecret is not set)
# For AgnosticV deployments, set rocketchat.existingSecret to the name of
# a secret created by AgnosticV containing:
#   - admin-password: RocketChat admin password
#   - tenant-password: Unique password for this tenant user
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workspace.rocketchat.secretName" . }}
  namespace: {{ .Values.namespacePrefix }}-{{ .Values.tenant.username }}
  labels:
    app.kubernetes.io/part-of: rocketchat
    app.kubernetes.io/component: credentials
    {{- include "workspace.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.rocketchat.adminPassword | quote }}
  tenant-password: {{ .Values.rocketchat.tenantPassword | quote }}
{{- end }}
