operators:
  leader-worker-set:
    channel: stable-v1.0
    installPlanApproval: Automatic
    namespace: openshift-lws-operator
    operatorGroup:
      enabled: true
    targetNamespaces:
      - openshift-lws-operator
