image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.2.5

defaultModelTiers:
  - free
  - premium
  - enterprise

models:
  - name: nvidia-nemotron-nano-9b-v2-fp8
    displayName: NVIDIA Nemotron Nano 9b v2 FP8
    uri: oci://registry.redhat.io/rhelai1/modelcar-nvidia-nemotron-nano-9b-v2-fp8-dynamic:1.5
    resources:
      limits:
        cpu: "6"
        memory: 48Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "4"
        memory: 32Gi
        nvidia.com/gpu: "1"
    extraArgs:
      - --enable-force-include-usage
      - --max-model-len=131072
      - --enable-auto-tool-choice
      - --tool-call-parser=qwen3_coder
      - --trust-remote-code
      - --reasoning-parser-plugin=/mnt/models/nano_v3_reasoning_parser.py
      - --reasoning-parser=nano_v3
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: l40-gpu
