tiers:
  free:
    tokenRateLimits:
      - limit: 100
        window: 1m
  premium:
    tokenRateLimits:
      - limit: 10000
        window: 1m
  enterprise:
    tokenRateLimits:
      - limit: 20000
        window: 1m
    users:
      - admin
