plans:
  free:
    ownerGroups:
      - system:authenticated
    tokenRateLimits:
      - limit: 10000
        window: 1m
      - limit: 100
        window: 1s
  premium:
    ownerGroups:
      - premium-users
    tokenRateLimits:
      - limit: 20000
        window: 1m
      - limit: 1000
        window: 1s
